server:
  port: 5555

spring:
  application:
    name: expense-service
  datasource:
    url: jdbc:postgresql://postgredb-1.cxpcrenyzzbl.us-east-2.rds.amazonaws.com:5432/jtraining?user=invauser&password=teVdInyxKGdJhRfOMip1&sslmode=require
  jpa:
    show-sql: true
    generate-ddl: false
# Swagger configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time: iso
#  notification-service
  activemq:
    #    user: admin
    #    password: admin
    #    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
      max-connections: 50
    packages:
      trust-all: true
  jms:
    pub-sub-domain: false
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: anchiao0417@gmail.com
    password: vgansukkzdfpxagi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
camel:
  springboot:
    xml-routes: classpath:./spring/camel-context.xml
#Enable debug level
logging:
  level:
    com.joanne.expenseservice: DEBUG


